config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    
    resources:book_comments, only:[:create, :destroy]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  
  validates :body, presence: true, length: { maximum: 200 }
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  attachment :profile_image
  
  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
   user_path(current_user.id)
  end


  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email]) # 注目
    end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    if comment.save
      redirect_to book_path(book)
    else 
      redirect_to book_path(book)
    end
  end 

  def destroy
    BookComment.find_by(id: params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end
  
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def new
    @book = Book.new
  end

  def create
    @book_comment = BookComment.new
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end


  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def new
    @user = User.new
    if @user.save
     flash[:notice] = "Welcome! You have signed up successfully."
     redirect_to user_path(@user.id)
    else
     render :new
    end
  end


  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

  end

  def index
    @users = User.all
    @book = Book.new

  end




  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <% if @book.errors.any? %>
          <%= @book.errors.count %>errors prohibited this obj from being saved
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>

  		  <h1>Editing Book</h1>

  		    <%= form_with model:@book, local: true do |f| %>
            <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <%= f.text_field :body %>
            </div>
            <div class="form-group">
              <%= f.submit 'Update Book' %>
            </div>
          <% end %>
        <%= link_to "Show",book_path(@book) %> |
    		<%= link_to "Back",books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

        <% if @book.errors.any? %>
          <%= @book.errors.count %>errors prohibited this obj from being saved
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>

        <h2>User info</h2>

        <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
	            <th>name</th>
          	  <th><%= current_user.name %></th>
            </tr>
            <tr>
	            <th>introduction</th>
	            <th><%= current_user.introduction %></th>
            </tr>
          </tbody>
        </table>

        <div class="row">
          <%= link_to '',edit_user_path(current_user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog edit_user_current_user.id' %>
        </div>




        <h2 class="mt-3">New book</h2>


        <%= form_with model: @book, local:true do |f| %>

          <h4>Title</h4>
          <%= f.text_field :title %>

          <h4>Opinion</h4>
          <%= f.text_area :body %>

          <%= f.submit 'Create Book' %>

        <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th>Comment</td>
              <th colspan="5"></th>
            </tr>
          </thead>


          <% @books.each do |book| %>
            <tbody>
              <tr>
                <td>
                  <%= link_to attachment_image_tag(book.user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg"),user_path(book.user) %>
                </td>
                <td>
                  <%= link_to book.title, book_path(book.id) %>
                </td>
                <td>
                  <%= book.body %>
                </td>
                
                <td>
                  <% if book.favorited_by?(current_user) %>
                    <p>
                      <%= link_to book_favorites_path(book), method: :delete do %>
                        <i class="fas fa-heart" style="color:red;"></i><%= book.favorites.count %>
                      <% end %>
                    </p>
                    <% else %>
                    <p>
                      <%= link_to book_favorites_path(book), method: :post do %>
                        <i class="fas fa-heart"></i><%= book.favorites.count %> 
                      <% end %>
                    </p>
                  <% end %>
                </td>
                <td>
                  <%= "コメント数: #{book.book_comments.count} " %>
                </td>
                 
                
              </tr>
            </tbody>
          <% end %>

        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <% if @book.errors.any? %>
          <%= @book.errors.count %>errors prohibited this obj from being saved
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        
        

        <h2>User info</h2>
        <table class="table">
          <tbody>
            <tr>
              <div class="row">
                <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
              </div>
            </tr>
            <tr>
	            <th>name</th>
          	  <th><%= @user.name %></th>
            </tr>
            <tr>
	            <th>introduction</th>
	            <th>
	              <%= @user.introduction %>
	            </th>
            </tr>
          </tbody>
        </table>

        <div class="row">
          <%= link_to '',edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog edit_user_@user.id' %>
        </div>



        <h2 class="mt-3">New book</h2>
        <%= form_with model: @newbook, local:true do |f| %>

          <h4>Title</h4>
          <%= f.text_field :title %>

          <h4>Opinion</h4>
          <%= f.text_area :body %>

          <%= f.submit 'Create Book' %>

        <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="5"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
                <%= link_to @user.name, user_path(@user.id) %>
              </td>

              <td>
                <%= link_to @book.title, book_path %>
              </td>

              <td>
                <%= @book.body %>
              </td>

              <% if @book.user_id == current_user.id %>
                <td><%= link_to "Edit", edit_book_path(@book)%></td>
                <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"} %></td>
              <% end %>
              
              <td>
                <% if @book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(@book), method: :delete do %>
                      <i class="fas fa-heart" style="color:red;"></i><%= @book.favorites.count %>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(@book), method: :post do %>
                      <i class="fas fa-heart"></i><%= @book.favorites.count %> 
                    <% end %>
                  </p>
                <% end %>
              </td>

              <td>
                <p>コメント件数：<%= @book.book_comments.count %></p>
              </td>


            </tr>
          </tbody>
        </table>

        <% @book.book_comments.each do |book_comment| %>
          <%= attachment_image_tag book_comment.user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no_image.jpg" %>
          
          <%= link_to book_comment.user.name, user_path(book_comment.user) %>
          <%= book_comment.comment %>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
          <% end %>
          </br>
        <% end %>

        <%= form_with(model:[@book,@book_comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
          </br>
          <%= f.submit "送信" %>
        <% end %>




      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<body>
  <main>
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
      </div>
    </div>
  </main>
</body>

app/views/homes/edit.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "current-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>

app/views/homes/top.html.erb
  <main>
    <p id="notice"></p>
      <div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
            <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
            <p>you can share and exchange  your opinions , inpressions , and emotions</p>
            <p> about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
              <div class="row">
                <%= link_to("Log in", new_user_session_path, {class: "btn btn-info btn-sm btn-block mb-3 sign_in"}) %>
              </div>
              <div class="row">
                <%= link_to("Sign up", new_user_registration_path, {class: "btn btn-success btn-sm btn-block sign_up"}) %>
              </div>
            </div>
          </div>
        </div>
      </div>
  </main>



</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to 'Bookers',root_path, class: 'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <%= link_to 'Home',user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
              <%= link_to 'Users',users_path, class: 'fas fa-users nav-link text-light' %>
              <%= link_to 'Books',books_path, class: 'fas fa-book-open nav-link text-light' %>
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light'%>
            </ul>
          </div>
        </div>
      </nav>
      <% else %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to 'Bookers',root_path, class: 'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <%= link_to 'Home',root_path, class: 'fas fa-home nav-link text-light' %>
              <%= link_to 'About',home_about_path, class: 'fas fa-link nav-link text-light' %>
              <%= link_to 'sign up',new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
              <%= link_to 'login',new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
            </ul>
          </div>
        </div>
      </nav>
      <% end %>
    </header>
    
        <% if flash[:notice] %>
          <p id="notice">
            <%= flash[:notice] %>
          </p>
        <% end %>

      <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>

</html>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <% if @user.errors.any? %>
          <%= @user.errors.count %>errors prohibited this obj from being saved
          <% @user.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
          <%= form_with model:@user, local:true do |f| %>
            <div class="form-group">
              <label for="inputName">Name</label>
              <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%>
            </div>
            <div class="form-group">
              <label for="inputImage">ProfileImage</label>
              <%= f.attachment_field :profile_image, placeholder: "Image" %> 
            </div>
    
            <div class="form-group">
              <label for="inputIntroduction">Introduction</label>
              <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction"%>
            </div>
    
            <div class="form-group">
              <%= f.submit "Update User" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</main>

  
  
  
  
   

app/views/users/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

        <% if @book.errors.any? %>
          <%= @book.errors.count %>errors prohibited this obj from being saved
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>

        <h2>User info</h2>
        <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
	            <th>name</th>
          	  <th><%= current_user.name %></th>
            </tr>
            <tr>
	            <th>introduction</th>
	            <th><%= current_user.introduction %></th>
            </tr>
          </tbody>
        </table>

        <div class="row">
          <%= link_to '',edit_user_path(current_user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog edit_user_current_user.id' %>
        </div>

        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book, local:true do |f| %>

          <h4>Title</h4>
          <%= f.text_field :title %>

          <h4>Opinion</h4>
          <%= f.text_area :body %>

          <%= f.submit 'Create Book' %>

        <% end %>
      </div>


      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @users.each do |user| %>
            <tbody>
              <tr>
                <td>
                  <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
                </td>
                <td>
                  <%= user.name %>
                </td>
                <td>
                  <%= link_to "Show", user_path(user.id) %>
                </td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

        <% if @book.errors.any? %>
          <%= @book.errors.count %>errors prohibited this obj from being saved
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>


        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>

            <tr>
	            <th>name</th>
          	  <th>
          	    <%= @user.name %>
          	  </th>
            </tr>
            <tr>
	            <th>introduction</th>
	            <th>
	              <%= @user.introduction %>
	            </th>
            </tr>
          </tbody>
        </table>

        <div class="row">
            <%= link_to '',edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog edit_user_@user.id' %>
        </div>

        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book, local:true do |f| %>

          <h4>Title</h4>
          <%= f.text_field :title %>

          <h4>Opinion</h4>
          <%= f.text_area :body %>

          <%= f.submit 'Create Book' %>

        <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="4"></th>
            </tr>
          </thead>
          <% @books.each do |book| %>
            <tbody>
              <tr>
                <td>
                  <%= link_to attachment_image_tag(book.user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg"),user_path(book.user) %>

                <td>
                  <%= link_to book.title, book_path(book) %>
                </td>
                <td>
                  <%= book.body %>
                </td>
                
                <td>
                  <% if book.favorited_by?(current_user) %>
                    <p>
                      <%= link_to book_favorites_path(book), method: :delete do %>
                        <i class="fas fa-heart" style="color:red;"></i><%= book.favorites.count %>
                      <% end %>
                    </p>
                    <% else %>
                    <p>
                      <%= link_to book_favorites_path(book), method: :post do %>
                        <i class="fas fa-heart"></i><%= book.favorites.count %> 
                      <% end %>
                    </p>
                  <% end %>
                </td>
                
                <td>
                  <p>コメント数：<%= book.book_comments.count %></p>
                </td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>